### ISSUE TITLE
Altitude 191024, is it correct?

### ISSUE THREAD

**Issue by santagada** [microsoft/p4vfs#7]
If I'm not mistaken this altitude is not in the official altitude documentation:

https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes

Also seems to be between two valid ranges, but outside of both. Is that intended?

**Comment by jessk-msft** [comment]
We are working with Windows File Systems and Filters Group to allocate a new altitude identifier for the P4VFS driver. We should have dedicated value soon.

**Comment by jessk-msft** [comment]
The P4VFS driver has been officially allocated an FSFilter HSM altitude of 189700, as we requested. It can be used as a one decimal value (ie, 189700.1, 189700.2, ...) if needed. The next major version of P4VFS will use this new altitude.

**Comment by jessk-msft** [comment]
Fixed in release 1.26.0.0
